# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1   # Declare a dependency on the welcome-orb
 
# define the jobs: sayHello and sayGoodbye
jobs:
  Hello-World:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run: 
          name: Hello World
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  I-Have-Code:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
  Run-With-Node:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: Running in a Unique Container
          command: |
            node -v
  Now-Complete:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'Do work once the approval has completed'
              
  sayGoodbye:
    docker:
      - image: cimg/node:14.10.1  # primary container to run job commands
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "goodbye world"
      - run: echo "PWD is $(hostname) - $PWD"
      - run: echo "goodbye, leaving now"


# call the jobs in workflow
workflows:
  myFlow:
    jobs:
      - Hello-World
      - I-Have-Code:
          requires:
            - Hello-World
      - Run-With-Node:
          requires:
            - Hello-World
      - Hold-For-Approval:
          requires:
            - Run-With-Node
            - I-Have-Code
      - Now-Complete:
          requires:
            - Hold-For-Approval
            
      - sayGoodbye
          requires:
            - Now-Complete