# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  welcome: circleci/welcome-orb@0.4.1   # Declare a dependency on the welcome-orb
  slack: circleci/slack@4.2.0           # Declare a dependency on the slack orb
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
  build:
    docker:
      - image: cimg/node:14.10.1  # primary container to run job commands
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "hello world"
      
